### ISSUE TITLE
cordova plugin add com.moust.cordova.videoplayer bad version

### ISSUE THREAD

**Issue by AlainBarthelemy** [moust/cordova-plugin-videoplayer#12]
Hi there !

Thank's for you usefull plugin. 
I installed it with the following command line

`cordova plugin add com.moust.cordova.videoplayer`

and unfortunately ran into some issue trying to call VideoPlayer.close().

Finally I figured out that the version installed via the latter command line wasn't featuring the close() method. 
I reinstalled it via 

`cordova plugin add https://github.com/moust/cordova-plugin-videoplayer.git`

an it solved my issue.

**Comment by moust** [comment]
Thanks for your feedback, I just published the last version of the plugin on Cordova Registry.
