### ISSUE TITLE
Need both nofullscreen and fullscreen.

### ISSUE THREAD

**Issue by sirius2013** [moust/cordova-plugin-videoplayer#30]
this plugin is supporting both no-fullscreen and fullscreen?
I need video playing as no-fullscreen when portrait mode and full screen when rotate as landscape mode like youtube/vimeo player.
Regards

**Comment by moust** [comment]
Honestly I don't use it for a long time so I don't remember exactly, but it seem to me it's possible if your app has rotation mode enable. The view will fit to the screen and the video too.
I encourage you to try it by yourself if you can.
