### ISSUE TITLE
Video player does not show up nor play video

### ISSUE THREAD

**Issue by asadwaheed1** [moust/cordova-plugin-videoplayer#39]
I am using ionic framework. I used this plugin and tried playing a local video with path 
file:///storage/2179-1C04/DCIM/Camera/20170816_143027.mp4 but its not playing it gives exception
"Unhandled Promise rejection:", source: file:///android_asset/www/build/polyfills.js
"Error: Uncaught (in promise): Prepare failed.: status=0x1", source: file:///android_asset/www/build/polyfills.js
What's the problem?
I want to be able to play video on both iOS and android. how can i achieve it?

**Comment by asadwaheed1** [comment]
I found out that it was not opening video because it didn't had access to external storage. I think its not the fault of this library so closing this issue.

**Comment by Ross-Rawlins** [comment]
How did you resolve this?
