### ISSUE TITLE
Property 'SCALING_MODE' does not exist on type 'typeof VideoPlayer'.

### ISSUE THREAD

**Issue by bhavinwebdesk** [moust/cordova-plugin-videoplayer#41]
Hello,

I like your plugin but I stuck while using SCALING_MODE option.

I tried following code:

`import { VideoPlayer } from '@ionic-native/video-player';
.
.
.
this.videoPlayer.play("https://www.quirksmode.org/html5/videos/big_buck_bunny.mp4",{
      scalingMode: VideoPlayer.SCALING_MODE.SCALE_TO_FIT_WITH_CROPPING
    }).then(() => {
      console.log('video completed');
      this.videoPlayer.close();
    }).catch(err => {
      console.log(err);
    });`

but I got error:

`Property 'SCALING_MODE' does not exist on type 'typeof VideoPlayer'. `

I can play video without providing any option though.

Thanks,
Bhavin

**Comment by piii866** [comment]
options scalingMode,here must be number

**Comment by Saqib92** [comment]
its like:

`VideoPlayer.play(
    "file:///android_asset/www/movie.mp4",
    {
        volume: 0.5,
        scalingMode: 1 or 2 // pass integer here
    },
    function () {
        console.log("video completed");
    },
    function (err) {
        console.log(err);
    }
);`
