### ISSUE TITLE
cannot download from plugin resgitry

### ISSUE THREAD

**Issue by shfaizanali** [moust/cordova-plugin-videoplayer#7]
the plugin is not available via plugin resgitry

**Comment by moust** [comment]
Strange, the plugin seem to have disappeared from the plugin registry.

Instead you can use the github url to add it to your project :
`cordova plugin add https://github.com/moust/cordova-plugin-videoplayer.git`

**Comment by shfaizanali** [comment]
there is also an issue with documentation. you have missed a , after error callback in 2nd example and in first example instead of play you are calling get

**Comment by shfaizanali** [comment]
I am getting the following error, Can you help me resolving it please
ERROR: Plugin 'VideoPlayer' not found, or is not a CDVPlugin. Check your plugin mapping in config.xml.

**Comment by moust** [comment]
I deduce you have this error when running your app on iOS. The plugin only works on Android.
For iOS you don't need to use this plugin and can use an html video element.
