### ISSUE TITLE
error: cannot find symbol variable R   location: class VERSION_CODES

### ISSUE THREAD

**Issue by msRajpura** [moust/cordova-plugin-videoplayer#72]
error: cannot find symbol
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) {
                                                        ^
  symbol:   variable R
  location: class VERSION_CODES

**Comment by msRajpura** [comment]
> error: cannot find symbol
> if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) {
> ^
> symbol: variable R
> location: class VERSION_CODES

**Comment by msmurgui** [comment]
Hey! Did you solve this issue? @msRajpura

**Comment by ayubUOL** [comment]
@msRajpura @msmurgui Did you guys able to solve it ?

**Comment by msmurgui** [comment]
@ayubUOL Hi! I was using IONIC v3 for an old app that my company developed. I ended up using another library: @ionic-native/video-player that wraps this library and makes its usage easier!
